// tslint:disable
/**
 * Lockdown app
 * This is the api for the lockdown app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nonem@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Address } from './address';
import { FamilyTicketPayload } from './family-ticket-payload';
import { FoodTicketPayload } from './food-ticket-payload';
import { HealthTicketPayload } from './health-ticket-payload';
import { HelpTicketPayload } from './help-ticket-payload';
import { RecreationTicketPayload } from './recreation-ticket-payload';
import { WorkTicketPayload } from './work-ticket-payload';

/**
 * @type TicketRequest
 * @export
 */
export type TicketRequest = FamilyTicketPayload | FoodTicketPayload | HealthTicketPayload | HelpTicketPayload | RecreationTicketPayload | WorkTicketPayload;



