// tslint:disable
/**
 * Lockdown app
 * This is the api for the lockdown app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nonem@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Address } from './address';

/**
 * 
 * @export
 * @interface TicketPayload
 */
export interface TicketPayload {
    /**
     * 
     * @type {string}
     * @memberof TicketPayload
     */
    hashIdentityNumber: string;
    /**
     * 
     * @type {number}
     * @memberof TicketPayload
     */
    userPin: number;
    /**
     * 
     * @type {Address}
     * @memberof TicketPayload
     */
    startPosition: Address;
    /**
     * 
     * @type {Address}
     * @memberof TicketPayload
     */
    finishPosition: Address;
    /**
     * 
     * @type {string}
     * @memberof TicketPayload
     */
    reason: string;
    /**
     * 
     * @type {string}
     * @memberof TicketPayload
     */
    signature: string;
    /**
     * 
     * @type {Date}
     * @memberof TicketPayload
     */
    leaveTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof TicketPayload
     */
    arrivalTime?: Date;
}


